# Setup
title: James Wong
tagline: mechanical engineer +
url: "https://jamestorrissonwong.github.io/jtw"
paginate: 1
baseurl: "jtw/"
permalink: :title/



kramdown:
    footnote_backlink: "&#10548;"




# Gems
plugins:
  - jekyll
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-remote-theme
  - jekyll-include-cache

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: James Wong
  url: 
  email: jtw2@andrew.cmu.edu

# Custom vars
version: 
github:
  repo: 
